version: '3.8'

services:
  flask:
    build: .
    image: online_yilbasi
    command: python3 wsgi.py
    container_name: yilbasi
    volumes:
      - .:/app
    ports:
      # maclerde sistem işlemlerinden biri bu portu kullanıyor ondan 5050
      - "5050:5000"
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - backend

  celery_worker:
    container_name: celery_worker
    hostname: celery_worker
    depends_on:
      - flask
      - redis
    image: online_yilbasi
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: sh -c "celery -A app.celery worker -l info"
    networks:
      - backend

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge